### ISSUE TITLE
SCIRun 5 perfomance issues

### ISSUE THREAD

**Issue by darrellswenson** [SCIInstitute/SCIRun#1541] opened 2016-08-12 17:30 UTC
I am currently running several very complex networks in SCIRun 4. I would like to transition to SCIRun 5 but at this point in time it is not possible because of performance issues with SCIRun 5. Here are a few observations. I downloaded the latest version of SCIRun 5, but these issues still persist.  I am running on windows 7.

SCIRun 5 crashes when reading in and writing out large data. I am not sure exactly where the threashold is but it seems at least 5x lower than SCIRun 4. On that note, SCIRun 4 also crashes when trying to write out files in a binary format in the GB range.

The same is true for visualization. On my system showfield can handle meshes with about 1 million nodes and 6 million elements in SCIRun 4. In SCIRun 5 it can only handle about 1/5 that size.

Locking Handles - In SCIRun 5 the locking handels do not seem to be working very well. When I have a network that iterates, such as building a leadfield matrix, I am not sure what exactly is going on, but each module takes several seconds to execute. In this case, most of them should not execute at all. Also, it reexecutes every module in the network regardless if it is connected to the updating module or not. So imagine if some of the modules take hours to compute. If I change a completely unrelated part of the network, I have to wait hours for the whole thing to complete.

Bug reports:

Readfield (tetvol) .pts .elem: Readfield hanges when trying to read a tetvol. These same volumes can be read by SCIRun4.

Setfield: This does not indicate that there is a problem when you try to set something that doesn't work. It just passes on garbage.

File selection dialog in many modules: This should save the file it was set to for that particular module. Right now it jumps to where ever you were last, independent of module.

Status Bar: This seems to get out of sync with the acutal errors in the network. It is constantly out of sync. It often says that the network is 50% done or something, but it really has finished.

![image](https://cloud.githubusercontent.com/assets/20995461/17630950/75b96442-6087-11e6-9348-c598d709db16.png)

TIMING LOG: execution began at 10:43:37.013
    Module ID,module time,total module time,total wall time
    ReadMatrix:0,0.045,0.045,0.107

SwapFieldData: Runs correctly the first time, but runs incorectly every time after that.

ViewScene: Many of our FE geometries created from other packages show up transparent, almost like the backface culling is backwards. In SCIRun 4 there is a way to switch this, we probably need this with SCIRun 5.
![image](https://cloud.githubusercontent.com/assets/20995461/17630938/66b22268-6087-11e6-9196-470df0a9e4b2.png)

**Comment by dcwhite** [comment] 2016-08-12 17:44
I'll break this issue into multiple issues and write a reply for each part.

**Comment by dcwhite** [comment] 2016-08-29 14:59
Reply from Darrell:
---
ow many modules in your typical network?
20+, However, I was seeing these problems with only around 15 or so.
 
Could you give me a range on the crash threshold for read/write? 1GB, 2GB, ?? And what type, is it Field, Matrix, both, or other?
I am not sure the exact threshold but we would like to be able to write 3.5 – 14 GB data into a .mat format or some other binary format. This is not possible in SCIRun5 or SCIRun4. SCIRun4 can handle this as a .txt file, though this is very slow. SCIRun5 does not seem to be able to handle this at all.
 
As for SCIRun fields, as .fld or .mat SCIRun5 cannot handle meshes on the order of 30 million elements, the threshold is MUCH lower than that. We have used SCIRun4 to read in meshes on the order of 250 million elements. (CARP has ridiculous resolution demands) we would never attempt to visualize this. We typically only visualize something (SCIRun4) with less than 5 million elements on my machine here. When I was at the U, my iMAC struggled with anything over 1 million. SCIRun5 is not even in the same ball park on this one.
 
 
Please tell me your system specs, CPU, main RAM and GPU card/VRAM
Everything I am testing is unstructured, so you may what to ask Jess or Brett for a large unstructured mesh. They are stored in memory very differently as you well know.
 
Specs:
 
Processor: Intel® Xeon® CPU E5-2623 v3 @ 3.00 GHz (2 processors) – (total of 16 CPUs)
64.0 GB or RAM
GPU: NVIDIA Quadro k5200, Integrated RAMDAC, Total memory 4095 MB
 
 
As far as visualization, here is a mesh that visualizes strange in SCIRun5, I cannot send this geometry, but
Ask Jess for a Peter Vandam torso meshed with tetgen from SCIRun4. This should reproduce the bug.

**Comment by jessdtate** [comment] 2016-09-29 19:22
Just to report it here before I forget.  The execute downstream only option needs to be in the sprocket menu, and/or should be the default of the execute button on the module.

**Comment by dcwhite** [comment] 2016-09-29 20:26
Good idea. I knew the execute-downstream action needed to be more visible/configurable, but just wanted to get it in quickly, so I will start with those suggestions.

**Comment by jessdtate** [comment] 2016-10-14 17:07
I've made a few tet meshes to test in the /home/sci/jess/mesh_testing/ directory.  The meshes are the same geometry with different resolution.  The number in the filename is the number of elements in the mesh.  I'm having trouble making meshes beyond the 52 million element range with sr4 or sr5.  sr4 has a writing problem, sr5 might be getting stuck on tetgen.

I can load in the 52 million element mesh in sr5 no problem.  It only takes a few seconds, and some of the other operations are fast (data manipulation) and some are slow (mapping) as expected.  I don't think I can visualize this size on my machine.  

Brett provided a larger mesh (29yo_Cleaver_LabelMapped.fld, 200 million elements) which I was able to load and perform the same operations.  As expected, everything was much slower.  Loading took a few minutes, and other things were scaled similarly.

When testing the visualization of the ~1 million element tet mesh, I found that SR5 was faster than SR4 in executing and updating the scene.  There is the problem with the edges for the hidden faces coming through in SR5 that Darrell mentioned.  This seems to be a precision problem, as it changes based on the zooming level. Both can do a ~1million trisurf mesh no problem.   I will see if I can find the limits of the visualization on my machine.

These test were done on my iMac (os x 10.10, NVIDIA GeForce GT 755M 1024 MB, 3.2 GHz Intel Core i5)

**Comment by jessdtate** [comment] 2016-10-14 17:08
I will keep trying to make bigger meshes.

**Comment by jessdtate** [comment] 2016-10-18 15:42
saving and loading big data using the matlab is not possible with the current libraries.  At least in matlab, saving a file of > 100 million elements requires the newest version of the .mat file (7.3), which I think uses compression.  there was a discussion about this a number of years ago, I think with @moritzdannhauer for scirun4.  I'm not sure if anything is different now.

**Comment by aylakhan** [comment] 2016-10-18 16:07
Matlab 7.3 can use compression, and I don't think anything has changed.

**Comment by jessdtate** [comment] 2016-10-18 16:18
I was able to load a 530 million element mesh  (fld format) into SR5, but it crashed when attempting a mapping module.  I think I ran out of memory on my machine.

**Comment by dcwhite** [comment] 2016-10-18 16:27
I will attach a link to a spreadsheet for loading (ReadField) and visualization (ShowField) execution times across all of our machines. Let me add some code that will make it easier to gather this data.

**Comment by dcwhite** [comment] 2016-10-31 19:53
> We have used SCIRun4 to read in meshes on the order of 250 million elements. (CARP has ridiculous resolution demands) we would never attempt to visualize this. ..... SCIRun5 is not even in the same ball park on this one.

As you can see in this [performance spreadsheet](https://docs.google.com/spreadsheets/d/1NY3BucpRKdWuUPV9vbl4o4fpUTyj6SgHHF3xWSfIFko/edit?usp=sharing), SCIRun 5 is mostly faster than 4 across various mesh sizes when executing ReadField. I'm still testing ShowField. Can you be more specific when you say 

> SCIRun5 cannot handle meshes on the order of 30 million elements

**Comment by jessdtate** [comment] 2016-12-02 17:34
I finally updated the spreadsheet with the specs form my computer

**Comment by dcwhite** [comment] 2016-12-02 19:24
Great! Could you update the other tabs as well? ShowField and SCIRun 4 times too.

**Comment by jessdtate** [comment] 2016-12-02 23:50
Oops.  Done now.

**Comment by dcwhite** [comment] 2019-04-01 16:38
I'll go over this one this week

**Comment by dcwhite** [comment] 2019-10-16 16:00
This one needs breaking up into sub-issues

**Comment by dcwhite** [comment] 2019-12-05 21:23
Closing since I've broken out all available sub-issues and we're still waiting for feedback from the client.

**Closed by dcwhite** 2019-12-05 21:23 UTC
Labels: Algorithms, Bug, Crash, Data Export, Data Import, Datatypes, Documentation, Enhancement, Framework, GUI, Graphics, Medtronic Project, Modules, Network, Performance, Priority-High, Required For Beta, Serialization
