### ISSUE TITLE
AutoReadFile string input

### ISSUE THREAD

**Issue by jab0707** [SCIInstitute/SCIRun#2223] opened 2021-02-02 20:52 UTC
It would be great if the AutoReadFile Module could have a string input. like readMatrix and readFiled, so that scripting of the network and control of what files are read in can be more readily organized, while still leveraging the advantage of the ease of use of the autoreadfile.

**Comment by dcwhite** [comment] 2021-02-02 21:57
Can the `Filename` state variable just be set directly through Python?

**Comment by jab0707** [comment] 2021-02-02 22:47
It can indeed, so that does work as a workaround

**Comment by dcwhite** [comment] 2021-12-09 16:43
Duplicate of #2270

**Closed by dcwhite** 2021-12-09 16:43 UTC
Labels: Enhancement, no-issue-activity
