### ISSUE TITLE
Controlling location of point probe widget between slices

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1627] opened 2017-05-12 21:32 UTC
Creating for @ajanson to fill in details.

**Comment by ajanson** [comment] 2017-05-22 17:28
SCIRun 4 functionality when moving a point probe that was generated in the center of the slice is to keep the new location until a new slice is selected. At that point the point probe is re-centered on the new slice and can be moved again.

SCIRun 5 does not let you move the point probe once it has been generated at the center of an object. Upon moving it it jumps back to the original center location. Intended functionality should be that it stays at the moved location.

Steps to reproduce:
CreateLatVol -> GetSliceFromStructuredFieldByIndices (+ShowField into ViewScene) -> GenerateSinglePointProbeFromField ( Positioning Method = Center; Pink Pipe into ViewScene)

Shift+Click and move the point probe in the ViewScene. The point probe will not actually move.
A workaround I just discovered is to have Positioning Method = Center when first executing to generate the point probe at the center of the slice, then switch to "Location" to be able to move the probe where you want. Also note that this Positioning method option does not exist in v4 so I'm not sure what the differences are between v4 and v5. 

Possible Solution: Right now Positioning Method = Node or Element exhibit the same functionality as Center. However, whenever I switch to Node or Element and re-execute the point probe snaps to the closest node or element on the slice. I would suggest leaving center as it is and changing the node and element functionality to snap to the closest node or element after I drag and drop the point probe. Note that this snapping also works when the point probe is positioned off of the slice and could also be a possible solution for #1626

**Comment by dcwhite** [comment] 2017-06-09 16:36
I'll work on this today.

**Closed** 2017-06-12 22:07 UTC
Labels: Modules
