### ISSUE TITLE
ShowGlyphs does not plot gradients in viewScene

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/SCIRun#1044] opened 2015-06-18 18:52 UTC
Tried calculating the gradient on the potentials from a surface mesh and then plotting them with showGlyphs.

The problem is that ShowGlyphs does not plot anything (even after selecting Show Vectors in the GUI).
The field generated with create gradients seems to have a reasonable field, but can't really validate that without being able to plot.

**Comment by dcwhite** [comment] 2015-06-18 18:59
I think this is a duplicate of ...(issue about cell-centered vectors)

**Comment by dcwhite** [comment] 2015-06-18 18:59
Please provide a more detailed description--what type of mesh, sample network, data, etc.

**Comment by jessdtate** [comment] 2019-03-13 20:35
@jcollfont data or network?

**Closed** 2019-04-16 22:12 UTC
Labels: Graphics
