### ISSUE TITLE
teem lib build fail due to pthead

### ISSUE THREAD

**Issue by pip010** [SCIInstitute/SCIRun#1164] opened 2015-08-03 14:33 UTC
I did successfully compile and run latest scirun5 on ubuntu14.04 however I have hard time replicating it on mint17. It seems cmake probing pthread fails:

/usr/bin/cc        CMakeFiles/cmTC_4ef83.dir/CheckSymbolExists.c.o  -o cmTC_4ef83 -rdynamic 
CMakeFiles/cmTC_4ef83.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[4]: *** [cmTC_4ef83] Error 1
make[4]: Leaving directory `/home/ppetrov/Documents/scirun5_build/Externals/teem/CMakeFiles/CMakeTmp'
make[3]: *** [cmTC_4ef83/fast] Error 2
make[3]: Leaving directory `/home/ppetrov/Documents/scirun5_build/Externals/teem/CMakeFiles/CMakeTmp'

File /home/ppetrov/Documents/scirun5_build/Externals/teem/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

I tried everything but regardless I keep bumping on the same issue.
I've tried disabling pthread support from: src/Externals/teem/CMakeLists.txt
but as if that file is not even touched :( even when I delete the build folder and run cmake again.

I doubt it is a cmake bug since I'm using latest 3.3.0 and gcc 4.9.2

ld -lpthead --verbose gives:
==================================================
attempt to open /usr/x86_64-linux-gnu/lib64/libpthread.so failed
attempt to open /usr/x86_64-linux-gnu/lib64/libpthread.a failed
attempt to open //usr/local/lib/x86_64-linux-gnu/libpthread.so failed
attempt to open //usr/local/lib/x86_64-linux-gnu/libpthread.a failed
attempt to open //usr/local/lib64/libpthread.so failed
attempt to open //usr/local/lib64/libpthread.a failed
attempt to open //lib/x86_64-linux-gnu/libpthread.so failed
attempt to open //lib/x86_64-linux-gnu/libpthread.a failed
attempt to open //lib64/libpthread.so failed
attempt to open //lib64/libpthread.a failed
attempt to open //usr/lib/x86_64-linux-gnu/libpthread.so succeeded
opened script file //usr/lib/x86_64-linux-gnu/libpthread.so
opened script file //usr/lib/x86_64-linux-gnu/libpthread.so
attempt to open /lib/x86_64-linux-gnu/libpthread.so.0 succeeded
/lib/x86_64-linux-gnu/libpthread.so.0
attempt to open /usr/lib/x86_64-linux-gnu/libpthread_nonshared.a succeeded
libc.so.6 needed by /lib/x86_64-linux-gnu/libpthread.so.0
found libc.so.6 at //lib/x86_64-linux-gnu/libc.so.6
ld-linux-x86-64.so.2 needed by /lib/x86_64-linux-gnu/libpthread.so.0
found ld-linux-x86-64.so.2 at //lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
ld: warning: cannot find entry symbol _start; not setting start address

any tips?

**Comment by pip010** [comment] 2015-08-07 08:52
OK. A small follow up on the issue. It is possible I have a corrupt build sys.
both:
ld -pthreads --verbose
ld -pthread --verbose
show ld cant find the pthreads lib on the ubuntu machine I successfully build latest scirun5.
This makes me think pthread is unrelated and it just happend to be the victim of a broken toolchain.
The cmake part about binfing to pthread looked a bit funny IMO, but I'm not cmake expert :)

Maybe close?

**Comment by aylakhan** [comment] 2015-08-27 20:04
That appears to be the most likely reason for this error, since I can't reproduce. Closing the issue.

**Closed by aylakhan** 2015-08-27 20:04 UTC
Labels: Build
