### ISSUE TITLE
incorrect render of cylinder edge glyphs for streamlines

### ISSUE THREAD

**Issue by behollis** [SCIInstitute/SCIRun#1445] opened 2016-05-25 17:41 UTC
[Pic](http://www.sci.utah.edu/~behollis/scirun5/cylinder-render-scirun5.png) of problem with network.

System:
Ubuntu 15.10
GeForce GTX Titan X

**Comment by cbrightsci** [comment] 2016-05-25 17:55
@behollis Please attach a link to the network and any data needed by the networks.

**Comment by cbrightsci** [comment] 2016-05-25 20:22
@behollis If you could give me an actual network that manifests this bug that would be wonderful. That way I can work with the network and debug through it. If any other files are needed for the network please provide those as well.

**Comment by behollis** [comment] 2016-05-25 20:23
here are the needed files (modified from distribution) to reproduce:

1. [network](http://www.sci.utah.edu/~behollis/scirun5/streamline.srn5)
2. [bdl](http://www.sci.utah.edu/~behollis/scirun5/Defib_simulation_results.bdl)

**Comment by behollis** [comment] 2016-06-07 17:16
Has this problem been verified yet?

**Comment by dcwhite** [comment] 2017-12-04 20:54
@jessdtate is investigating

**Comment by dcwhite** [comment] 2018-07-16 20:23
Duplicate of #1815 
Close this one when PR is merged

**Closed** 2018-07-18 15:45 UTC
Labels: Graphics
