### ISSUE TITLE
Incremental theta change completely resets position

### ISSUE THREAD

**Issue by 9595015** [SCIInstitute/SCIRun#1483] opened 2016-06-30 18:06 UTC
### Prerequisites

* [x] Are you running the [latest version of SCIRun](https://github.com/SCIInstitute/SCIRun/releases)?
[//]: # (* [ ] TODO: Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?)
[//]: # (* [ ] TODO: Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?)
* [x] Are you reporting to the [correct repository](https://github.com/SCIInstitute/SCIRun)?
* [x] Did you [perform a cursory search](https://github.com/SCIInstitute/SCIRun/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide. These links point to another project, but most of the advice holds in general.

### Description

[Description of the bug or feature]

For Mac crash bugs, please *DO NOT* paste an entire MacOS crash report here. Edit it down to just the stack trace of the thread that crashed, along with the general system info on the top.

**In all bug cases, some combination of screenshots, sample network(s), and input data should be attached. You can use any cloud storage links you want for networks and data.**

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `SCIRun --version` at the command line, or clicking on the version button in the bottom right corner of the GUI (which copies the version to the clipboard). Also, please include the OS and what version of the OS you're running.

**Comment by aylakhan** [comment] 2016-06-30 18:28
Duplicate of #1483?

**Closed** 2016-06-30 18:40 UTC
Labels: Duplicate
