### ISSUE TITLE
Torso tank BEM network validation

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#1005] opened 2015-06-04 06:18 UTC
The Forward/Inverse toolkit network torso-tank-bem needs validation.

**Comment by aylakhan** [comment] 2015-06-08 21:25
Emphasis should be on output of torso-tank-bem module. See also #1018.

**Comment by aylakhan** [comment] 2015-06-19 05:13
FYI toolkit networks have been moved to the [FwdInvToolkit] repo (https://github.com/SCIInstitute/FwdInvToolkit) (see #925).

**Comment by aylakhan** [comment] 2015-10-13 19:26
Any updates on this?

**Comment by zaracay** [comment] 2015-10-14 13:11
I'd forgotten about it.  I'm in the middle of reviewing a paper for Rob first, then I'll return to this.  It should be a few days.

Brett Burton

PhD Candidate in Bioengineering | University of Utah
www.sci.utah.edu/~bburton
www.linkedin.com/in/brettmburton/

**Comment by jessdtate** [comment] 2016-01-22 23:56
The BEM module appears to be giving the wrong solutions.  It doesn't match the FEM solutions when it should.  It also doesn't match know solutions to the concentric sphere model.  there is some matlab code (in scirun 4) that is more accurate.

**Comment by dcwhite** [comment] 2016-02-12 20:12
Any updates on this issue? Is the SCIRun code producing numbers that are way off, or close, or what?

**Comment by jessdtate** [comment] 2016-02-12 21:01
There is something wrong with the BEM module.  The outputs are pretty far off expected analytical solutions.  I haven't been able to figure out exactly what the problem is though.

**Comment by aylakhan** [comment] 2016-06-17 20:27
@jessdtate - does your pull request completely fix this?

**Comment by jessdtate** [comment] 2016-06-17 20:35
yes.  There are some aspects of the code (deflation of the matrix) that I took out, but may need to be revisited later, perhaps as an optional feature.

**Comment by zaracay** [comment] 2016-06-24 21:38
I ran simulations on 2 region BEM (heart to torso) solutions using the 771 closed tank and 337 closed sock to test the 4 surface normal cases (inward or outward pointing for both surfaces).  The two solutions with measurement surface normals facing in appeared to be correct, but having **both source and measurement normals pointing inward** produced results that were most closely correlated to FEM solutions.  I used several source representations to confirm this.

**Comment by zaracay** [comment] 2016-06-24 21:40
On a different note. In past tests, having more than 2 surfaces appeared to create incorrect results.  Further testing is needed on this.

**Comment by dcwhite** [comment] 2016-07-05 20:54
@jessdtate @zaracay Is this one ready to close?

**Comment by zaracay** [comment] 2016-07-05 21:00
The algorithm works for 2 surfaces but not for more than 2.  Also, the solution requires that all surface normals be pointing in the inward direction.  This is against the standard analytical procedure which requires surface normals to be pointing outwardly.  It’s probably just a sign difference somewhere in the algorithm.

So I think it remains open.

It works well enough to use it for our examples at IBBM, but the two quirks above should probably be resolved before we close out the ticket.  

Brett Burton

PhD Candidate in Bioengineering | University of Utah
www.sci.utah.edu/~bburton
www.linkedin.com/in/brettmburton/

**Comment by dcwhite** [comment] 2016-07-06 15:06
Thanks Brett.

**Comment by dcwhite** [comment] 2016-09-22 18:28
@jessdtate @zaracay Could one of you guys attach some test networks here that demonstrate the quirks mentioned above?

**Comment by dcwhite** [comment] 2017-11-06 21:04
@jessdtate wants to close this issue. Any objections @zaracay?

**Closed** 2017-11-13 20:52 UTC
Labels: IBBM, needs project, Testing, User Testing
