### ISSUE TITLE
ConvertComplexToRealMatrix

### ISSUE THREAD

**Issue by moritzdannhauer** [SCIInstitute/SCIRun#1587] opened 2017-02-08 14:58 UTC
We need this module as a counterpart of 'ConvertRealToComplexMatrix' (also) in order to be able to export it from SCIRun5.

**Comment by dcwhite** [comment] 2017-02-08 18:03
Duplicate of #1371, already assigned to you.

**Closed by dcwhite** 2017-02-08 18:03 UTC
